# Podstawy NumPy
## Tablica NumPy

In [1]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

In [2]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [3]:
# Najpierw importujemy NumPy
import numpy as np

In [4]:
# Tworząc tablicę z prostej listy, otrzymamy tablicę jednowymiarową
array1 = np.array([10, 100, 1000.])

In [5]:
# Tworząc tablicę z listy zagnieżdżonej, otrzymamy tablicę dwuwymiarową
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

In [6]:
# typ danych tablicy
array1.dtype

dtype('float64')

In [7]:
# przekonwertowanie typu danych
float(array1[0])

10.0

## Wektoryzacja i rozgłaszanie

In [8]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [9]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

In [11]:
array2 @ array2.T  # array2.T to skrót od array2.transpose()

array([[14., 32.],
       [32., 77.]])

## Funkcje uniwersalne

In [12]:
import math

In [13]:
math.sqrt(array2)  # Spowoduje to zgłoszenie błędu

TypeError: only size-1 arrays can be converted to Python scalars

In [14]:
# zagnieżdżona pętla
np.array([[math.sqrt(i) for i in row] for row in array2])

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [15]:
np.sqrt(array2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [16]:
array2.sum(axis=0)  # Zwraca jednowymiarową tablicę

array([5., 7., 9.])

In [17]:
# suma całej tablicy
array2.sum()

21.0

## Pobieranie i wybieranie elementów tablicy

In [18]:
array1[2]  # Zwraca skalar

1000.0

In [19]:
array2[0, 0]  # Zwraca skalar

1.0

In [20]:
array2[:, 1:]  # Zwraca tablicę dwuwymiarową

array([[2., 3.],
       [5., 6.]])

In [21]:
array2[:, 1]  # Zwraca tablicę jednowymiarową

array([2., 5.])

In [22]:
array2[1, :2]  # Zwraca tablicę jednowymiarową

array([4., 5.])

## Przydatne konstruktory tablicowe

In [23]:
np.arange(2 * 5).reshape(2, 5)  # 2 wiersze, 5 kolumn

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.random.randn(2, 3)  # 2 wiersze, 3 kolumny

array([[ 2.46810384, -1.13122088,  1.053042  ],
       [ 1.24830963,  1.08045364, -1.15139993]])

## Widok a kopia

In [25]:
array2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [26]:
subset = array2[:, :2]
subset

array([[1., 2.],
       [4., 5.]])

In [27]:
subset[0, 0] = 1000

In [28]:
subset

array([[1000.,    2.],
       [   4.,    5.]])

In [29]:
array2

array([[1000.,    2.,    3.],
       [   4.,    5.,    6.]])