In [1]:
# tworzenie listy
my_list = [4, 1, 5, 2]
my_list

[4, 1, 5, 2]

In [2]:
# sprawdzenie typu
type(my_list)

list

In [3]:
my_mixed_list = [1, 2, 3, ['Boo!', True]]
type(my_mixed_list)

list

In [4]:
my_list * 2

[4, 1, 5, 2, 4, 1, 5, 2]

In [5]:
# import biblioteki NumPy
import numpy

In [6]:
# tworzenie tablicy
my_array = numpy.array([4, 1, 5, 2])
my_array

array([4, 1, 5, 2])

In [7]:
# porównanie listy i tablicy

In [8]:
type(my_list)

list

In [9]:
type(my_array)

numpy.ndarray

In [10]:
my_list * 2

[4, 1, 5, 2, 4, 1, 5, 2]

In [11]:
my_array * 2

array([ 8,  2, 10,  4])

In [12]:
my_coerced_array = numpy.array([1, 2, 3, 'Boo!'])
my_coerced_array

array(['1', '2', '3', 'Boo!'], dtype='<U11')

In [13]:
# aliasy
import numpy as np

In [14]:
import numpy as np
# Biblioteka numpy również zawiera funkcję sqrt()
np.sqrt(my_array)

array([2.        , 1.        , 2.23606798, 1.41421356])

In [15]:
# Pobieramy drugi element... tak?
my_array[2]

5

In [16]:
my_array

array([4, 1, 5, 2])

In [17]:
# *Teraz* pobierzmy właściwy drugi element
my_array[1]

1

In [18]:
# Pobieranie elementów od drugiego do czwartego... tak?
my_array[1:3]

array([1, 5])

In [19]:
# *Teraz* pobierzemy elementy od drugiego do czwartego
my_array[1:4]

array([1, 5, 2])

In [20]:
# import biblioteki pandas
import pandas as pd

In [21]:
# ramka danych
record_1 = np.array(['Jack', 182, False])
record_2 = np.array(['Jill', 165, True])
record_3 = np.array(['Billy', 172, False])
record_4 = np.array(['Susie', 175, False])
record_5 = np.array(['Johnny', 168, False])
        
roster = pd.DataFrame(data = [record_1, 
                              record_2, record_3, record_4,record_5],
                                columns = ['imię', 'wzrost', 'ranny'])

roster

imię wzrost  ranny
0    Jack    182  False
1    Jill    165   True
2   Billy    172  False
3   Susie    175  False
4  Johnny    168  False

In [22]:
# pakiet seaborn
import seaborn as sns
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [23]:
# wyświetlenie pierwszych 5 wierszy z ramki
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [24]:
# importowanie danych

In [25]:
import os

In [26]:
os.path.isfile('plik-testowy.csv')

True

In [27]:
os.path.isfile('folder-testowy/plik-testowy.csv')

True

In [28]:
# Otrzymasz False jeżeli plik testowy nie znajduje się o katalog wyżej w ścieżce
os.path.isfile('../plik-testowy.csv')

False

In [29]:
# wczytanie pliku star
star = pd.read_excel('dane/star.xlsx')
star.head()

wynik.matematyka  wynik.czytanie  \
0               473             447   
1               536             450   
2               463             439   
3               559             448   
4               489             447   

                                     rodzaj.klasy  doświadczenie.nauczyciela  \
0                                      mała.klasa                          7   
1                                      mała.klasa                         21   
2  standardowa.klasa.z.nauczycielem.wspomagającym                          0   
3                               standardowa.klasa                         16   
4                                      mała.klasa                          5   

          płeć darmowe.wyżywienie.w.szkole    rasa  id.szkoły  
0  dziewczynka                         nie   biała         63  
1  dziewczynka                         nie  czarna         20  
2     chłopiec                         tak  czarna         19  
3     chłopiec                         nie   biała         69  
4     chłopiec                         tak   biała         79

In [30]:
# wczytanie pliku okręgi
districts = pd.read_csv('dane/okręgi.csv')
districts.head()

id.szkoły     nazwa_szkoły     hrabstwo
0          1          Rosalia  New Liberty
1          2  Montgomeryville       Topton
2          3             Davy     Wahpeton
3          4         Steelton    Palestine
4          6       Tolchester      Sattley

In [31]:
# informacje o danych
star.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5748 entries, 0 to 5747
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   wynik.matematyka             5748 non-null   int64 
 1   wynik.czytanie               5748 non-null   int64 
 2   rodzaj.klasy                 5748 non-null   object
 3   doświadczenie.nauczyciela    5748 non-null   int64 
 4   płeć                         5748 non-null   object
 5   darmowe.wyżywienie.w.szkole  5748 non-null   object
 6   rasa                         5748 non-null   object
 7   id.szkoły                    5748 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 359.4+ KB


In [32]:
# statystyki opisowe
star.describe()

wynik.matematyka  wynik.czytanie  doświadczenie.nauczyciela  \
count       5748.000000     5748.000000                5748.000000   
mean         485.648051      436.742345                   9.307411   
std           47.771531       31.772857                   5.767700   
min          320.000000      315.000000                   0.000000   
25%          454.000000      414.000000                   5.000000   
50%          484.000000      433.000000                   9.000000   
75%          513.000000      453.000000                  13.000000   
max          626.000000      627.000000                  27.000000   

         id.szkoły  
count  5748.000000  
mean     39.836639  
std      22.957552  
min       1.000000  
25%      20.000000  
50%      39.000000  
75%      60.000000  
max      80.000000

In [33]:
star.describe(include = 'all')

wynik.matematyka  wynik.czytanie  \
count        5748.000000     5748.000000   
unique               NaN             NaN   
top                  NaN             NaN   
freq                 NaN             NaN   
mean          485.648051      436.742345   
std            47.771531       31.772857   
min           320.000000      315.000000   
25%           454.000000      414.000000   
50%           484.000000      433.000000   
75%           513.000000      453.000000   
max           626.000000      627.000000   

                                          rodzaj.klasy  \
count                                             5748   
unique                                               3   
top     standardowa.klasa.z.nauczycielem.wspomagającym   
freq                                              2015   
mean                                               NaN   
std                                                NaN   
min                                                NaN   
25%                                                NaN   
50%                                                NaN   
75%                                                NaN   
max                                                NaN   

        doświadczenie.nauczyciela      płeć darmowe.wyżywienie.w.szkole  \
count                 5748.000000      5748                        5748   
unique                        NaN         2                           2   
top                           NaN  chłopiec                         nie   
freq                          NaN      2954                        2973   
mean                     9.307411       NaN                         NaN   
std                      5.767700       NaN                         NaN   
min                      0.000000       NaN                         NaN   
25%                      5.000000       NaN                         NaN   
50%                      9.000000       NaN                         NaN   
75%                     13.000000       NaN                         NaN   
max                     27.000000       NaN                         NaN   

         rasa    id.szkoły  
count    5748  5748.000000  
unique      3          NaN  
top     biała          NaN  
freq     3869          NaN  
mean      NaN    39.836639  
std       NaN    22.957552  
min       NaN     1.000000  
25%       NaN    20.000000  
50%       NaN    39.000000  
75%       NaN    60.000000  
max       NaN    80.000000

In [34]:
# Pierwszy wiersz i pierwsza kolumna ramki danych
roster.iloc[0,0]

'Jack'

In [35]:
# Wiersze od drugiego do czwartego, kolumny od pierwszej do trzeciej
roster.iloc[1:4, 0:3]

imię wzrost  ranny
1   Jill    165   True
2  Billy    172  False
3  Susie    175  False

In [36]:
# Wszystkie wiersze z kolumny imię
roster.loc[:, 'imię']

0      Jack
1      Jill
2     Billy
3     Susie
4    Johnny
Name: imię, dtype: object

In [37]:
# Zapis ramek danych 
roster.to_csv('dane-wyjsciowe/roster-python.csv')
roster.to_excel('dane-wyjsciowe/roster-python.xlsx')